[platformio]
default_envs = application

[env]
platform = ststm32
board = genericSTM32F103RB
framework = stm32cube

[env:application]
lib_deps = /Users/umairwanware/Desktop/FreeRTOS-Kernel
build_flags =
    -I/Users/umairwanware/Desktop/FreeRTOS-Kernel/include
    -I/Users/umairwanware/Desktop/FreeRTOS-Kernel/portable/GCC/ARM_CM3
board_build.ldscript = linker/STM32F103RBTX_APP.ld
build_src_filter =
    +<main.cpp>
    -<bootloader_main.cpp>

[env:bootloader]
board_build.ldscript = linker/STM32F103RBTX_BOOT.ld
build_src_filter =
    +<bootloader_main.cpp>
    -<application_main.cpp>